notify of install failure

diff --git a/ReEnroller/1/postinstall b/ReEnroller/1/postinstall
--- a/ReEnroller/1/postinstall
+++ b/ReEnroller/1/postinstall
@@ -19,6 +19,12 @@ if [ -e /private/var/root/Library/Preferences/com.jamf.pse.ReEnroller.plist ];th
     rm /private/var/root/Library/Preferences/com.jamf.pse.ReEnroller.plist
 fi
 
+if [ ! -d "/Library/Application Support/JAMF/ReEnroller/ReEnroller.app" ]; then
+    logger -t ReEnroller -f /var/log/jamf.log "ReEnroller app failed to install"
+    echo "ReEnroller app failed to install"
+    exit 1
+fi
+
 if [[ ${osvers_major} -ge 11 ]]; then
     launchctl bootstrap system /Library/LaunchDaemons/com.jamf.ReEnroller.plist
 else
diff --git a/ReEnroller/2/postinstall b/ReEnroller/2/postinstall
--- a/ReEnroller/2/postinstall
+++ b/ReEnroller/2/postinstall
@@ -5,3 +5,9 @@ chmod -R 750 "/Library/Application Support/JAMF/ReEnroller"
 if [ -e /private/var/root/Library/Preferences/com.jamf.pse.ReEnroller.plist ];then
     rm /private/var/root/Library/Preferences/com.jamf.pse.ReEnroller.plist
 fi
+
+if [ ! -d "/Library/Application Support/JAMF/ReEnroller/ReEnroller.app" ]; then
+    logger -t ReEnroller -f /var/log/jamf.log "ReEnroller app failed to install"
+    echo "ReEnroller app failed to install"
+    exit 1
+fi
